SEED_PATIENTS = [
    {
        "id": "seed-001",
        "name": "Rohan Verma",
        "age": 34,
        "gender": "male",
        "chiefComplaint": "Found unresponsive at the scene after a motorcycle accident.",
        "consciousness": "U",
        "breathingStatus": "labored",
        "traumaSeverity": "severe",
        "vitals": {"heartRate": 130, "bpSystolic": 82, "bpDiastolic": 54, "temperature": 36.2, "spo2": 85, "respRate": 28},
        "history": {"medicalHistory": [], "medications": [], "allergies": []},
        "expectedSeverityLevel": 1,
    },
    {
        "id": "seed-002",
        "name": "Baby Ananya",
        "age": 0.15,
        "gender": "female",
        "chiefComplaint": "Fussy and unusually warm, feeding poorly since this morning.",
        "consciousness": "A",
        "breathingStatus": "normal",
        "traumaSeverity": "none",
        "vitals": {"heartRate": 150, "bpSystolic": None, "bpDiastolic": None, "temperature": 38.5, "spo2": 97, "respRate": 42},
        "history": {"medicalHistory": [], "medications": [], "allergies": []},
        "expectedSeverityLevel": 1,
    },
    {
        "id": "seed-003",
        "name": "Kabir Shah",
        "age": 6,
        "gender": "male",
        "chiefComplaint": "Wheezing and coughing badly, says he can't catch his breath.",
        "consciousness": "A",
        "breathingStatus": "labored",
        "traumaSeverity": "none",
        "vitals": {"heartRate": 132, "bpSystolic": 98, "bpDiastolic": 60, "temperature": 37.1, "spo2": 91, "respRate": 46},
        "history": {"medicalHistory": ["Asthma"], "medications": ["Albuterol inhaler"], "allergies": []},
        "expectedSeverityLevel": 2,
    },
    {
        "id": "seed-004",
        "name": "Prakash Iyer",
        "age": 78,
        "gender": "male",
        "chiefComplaint": "Crushing chest pain radiating to the left arm, started 20 minutes ago.",
        "consciousness": "A",
        "breathingStatus": "normal",
        "traumaSeverity": "none",
        "vitals": {"heartRate": 112, "bpSystolic": 96, "bpDiastolic": 58, "temperature": 36.9, "spo2": 93, "respRate": 22},
        "history": {"medicalHistory": ["Hypertension", "High cholesterol"], "medications": ["Atorvastatin"], "allergies": []},
        "expectedSeverityLevel": 1,
    },
    {
        "id": "seed-005",
        "name": "Meera Nair",
        "age": 29,
        "gender": "female",
        "chiefComplaint": "Cut my hand on a kitchen knife, bleeding has mostly stopped.",
        "consciousness": "A",
        "breathingStatus": "normal",
        "traumaSeverity": "minor",
        "vitals": {"heartRate": 74, "bpSystolic": 118, "bpDiastolic": 76, "temperature": 36.8, "spo2": 99, "respRate": 16},
        "history": {"medicalHistory": [], "medications": [], "allergies": []},
        "expectedSeverityLevel": 5,
    },
    {
        "id": "seed-006",
        "name": "Arjun Malhotra",
        "age": 41,
        "gender": "male",
        "chiefComplaint": "Just don't feel right today, hard to explain what's wrong.",
        "consciousness": "A",
        "breathingStatus": "normal",
        "traumaSeverity": "none",
        "vitals": {"heartRate": None, "bpSystolic": None, "bpDiastolic": None, "temperature": None, "spo2": None, "respRate": None},
        "history": {"medicalHistory": [], "medications": [], "allergies": []},
        "expectedSeverityLevel": 3,
    },
    {
        "id": "seed-007",
        "name": "Sunita Rao",
        "age": 55,
        "gender": "female",
        "chiefComplaint": "Severe abdominal pain since this morning, some vomiting.",
        "consciousness": "A",
        "breathingStatus": "normal",
        "traumaSeverity": "none",
        "vitals": {"heartRate": 106, "bpSystolic": 110, "bpDiastolic": 70, "temperature": 37.3, "spo2": 97, "respRate": 20},
        # First-time patient, no records on file - zero-history case.
        "history": {"medicalHistory": [], "medications": [], "allergies": []},
        # Severe abdominal pain + vomiting with stable-ish vitals (no
        # hypotension, no hypoxia) is commonly ESI-3 ("Urgent") absent
        # hemodynamic instability or peritoneal signs.
        "expectedSeverityLevel": 3,
    },
    {
        "id": "seed-008",
        "name": "Devendra Singh",
        "age": 82,
        "gender": "male",
        "chiefComplaint": "Fell at home, unable to bear weight on his hip, suspected fracture.",
        "consciousness": "A",
        "breathingStatus": "normal",
        "traumaSeverity": "minor",
        "vitals": {"heartRate": 88, "bpSystolic": 132, "bpDiastolic": 80, "temperature": 36.9, "spo2": 96, "respRate": 18},
        "history": {"medicalHistory": ["Osteoporosis"], "medications": ["Calcium supplement"], "allergies": []},
        "expectedSeverityLevel": 3,
    },
    {
        "id": "seed-009",
        "name": "Farah Khan",
        "age": 24,
        "gender": "female",
        "chiefComplaint": "Swelling of the face and throat after eating peanuts, hives all over.",
        "consciousness": "A",
        "breathingStatus": "labored",
        "traumaSeverity": "none",
        "vitals": {"heartRate": 140, "bpSystolic": 84, "bpDiastolic": 50, "temperature": 37.0, "spo2": 90, "respRate": 30},
        "history": {"medicalHistory": [], "medications": [], "allergies": ["Peanuts"]},
        "expectedSeverityLevel": 1,
    },
    {
        "id": "seed-010",
        "name": "Ishaan Gupta",
        "age": 4,
        "gender": "male",
        "chiefComplaint": "Fever and chills for two days.",
        "consciousness": "A",
        "breathingStatus": "normal",
        "traumaSeverity": "none",
        "vitals": {"heartRate": 128, "bpSystolic": 96, "bpDiastolic": 58, "temperature": 39.2, "spo2": 97, "respRate": 26},
        "history": {"medicalHistory": [], "medications": [], "allergies": []},
        "expectedSeverityLevel": 3,
    },
    {
        "id": "seed-011",
        "name": "Vikram Chatterjee",
        "age": 61,
        "gender": "male",
        "chiefComplaint": "Sudden slurred speech and weakness on one side of the body.",
        "consciousness": "A",
        "breathingStatus": "normal",
        "traumaSeverity": "none",
        "vitals": {"heartRate": 95, "bpSystolic": 162, "bpDiastolic": 96, "temperature": 37.0, "spo2": 96, "respRate": 18},
        "history": {"medicalHistory": ["Hypertension"], "medications": ["Amlodipine"], "allergies": []},
        "expectedSeverityLevel": 1,
    },
    {
        "id": "seed-012",
        "name": "Baby Ritvik",
        "age": 0.5,
        "gender": "male",
        "chiefComplaint": "Mild cold symptoms, runny nose, still feeding well.",
        "consciousness": "A",
        "breathingStatus": "normal",
        "traumaSeverity": "none",
        "vitals": {"heartRate": 128, "bpSystolic": None, "bpDiastolic": None, "temperature": 37.0, "spo2": 98, "respRate": 34},
        "history": {"medicalHistory": [], "medications": [], "allergies": []},
        "expectedSeverityLevel": 4,
    },
    {
        "id": "seed-013",
        "name": "Lakshmi Pillai",
        "age": 88,
        "gender": "female",
        "chiefComplaint": "Increasing confusion and lethargy over the last two days.",
        "consciousness": "V",
        "breathingStatus": "normal",
        "traumaSeverity": "none",
        "vitals": {"heartRate": 102, "bpSystolic": 104, "bpDiastolic": 66, "temperature": 38.3, "spo2": 95, "respRate": 20},
        "history": {"medicalHistory": ["Mild cognitive impairment"], "medications": [], "allergies": []},
        "expectedSeverityLevel": 2,
    },
    {
        "id": "seed-014",
        "name": "Aditya Kulkarni",
        "age": 33,
        "gender": "male",
        "chiefComplaint": "Twisted ankle playing basketball, swollen, can bear some weight.",
        "consciousness": "A",
        "breathingStatus": "normal",
        "traumaSeverity": "minor",
        "vitals": {"heartRate": 76, "bpSystolic": 120, "bpDiastolic": 78, "temperature": 36.7, "spo2": 99, "respRate": 15},
        "history": {"medicalHistory": [], "medications": [], "allergies": []},
        "expectedSeverityLevel": 5,
    },
    {
        "id": "seed-015",
        "name": "Sameer Ansari",
        "age": 27,
        "gender": "male",
        "chiefComplaint": "Stab wound to the abdomen, bleeding heavily.",
        "consciousness": "A",
        "breathingStatus": "labored",
        "traumaSeverity": "severe",
        "vitals": {"heartRate": 126, "bpSystolic": 86, "bpDiastolic": 52, "temperature": 36.5, "spo2": 90, "respRate": 26},
        "history": {"medicalHistory": [], "medications": [], "allergies": []},
        "expectedSeverityLevel": 1,
    },
    {
        "id": "seed-016",
        "name": "Diya Reddy",
        "age": 3,
        "gender": "female",
        "chiefComplaint": "Toddler just seems off today, not acting like herself.",
        "consciousness": "A",
        "breathingStatus": "normal",
        "traumaSeverity": "none",
        "vitals": {"heartRate": None, "bpSystolic": None, "bpDiastolic": None, "temperature": None, "spo2": None, "respRate": None},
        "history": {"medicalHistory": [], "medications": [], "allergies": []},
        "expectedSeverityLevel": 3,
    },
    {
        "id": "seed-017",
        "name": "Neha Joshi",
        "age": 52,
        "gender": "female",
        "chiefComplaint": "Sudden palpitations and dizziness for the last hour.",
        "consciousness": "A",
        "breathingStatus": "normal",
        "traumaSeverity": "none",
        "vitals": {"heartRate": 156, "bpSystolic": 128, "bpDiastolic": 82, "temperature": 37.0, "spo2": 97, "respRate": 18},
        "history": {"medicalHistory": [], "medications": [], "allergies": []},
        "expectedSeverityLevel": 2,
    },
    {
        "id": "seed-018",
        "name": "Ramesh Bhatt",
        "age": 70,
        "gender": "male",
        "chiefComplaint": "Chronic lower back pain that has been worsening over the past week.",
        "consciousness": "A",
        "breathingStatus": "normal",
        "traumaSeverity": "none",
        "vitals": {"heartRate": 82, "bpSystolic": 136, "bpDiastolic": 84, "temperature": 36.9, "spo2": 96, "respRate": 16},
        "history": {"medicalHistory": ["Osteoarthritis"], "medications": ["Paracetamol"], "allergies": []},
        "expectedSeverityLevel": 4,
    },
]
